package edu.banditutorials.beveragebar;

import java.util.Scanner;

/**
 * This App is a simulation created by the 542 team.
 *
 * @author Ajay Bandi
 */
public class App {

    // Specify welcome message
    private static final String GREETING_MESSAGE = "Welcome to our 542 Quenchers!";

    // Specify how to exit message
    private static final String ESCAPE_MESSAGE = "Hit Q to exit.";

    // Specify goodbye string
    private static final String GOODBYE_MESSAGE = "Thank you for visiting!";

    // specify number of  custom types available - UPDATE AS IT GROWS! 
    private static final int NUMBER_CUSTOM_TYPES = 3;

    /**
     * This main() method is the entry point for our application.
     *
     * @param args - inputs provided to the program (none required)
     */
    public static void main(String[] args) {

        // output welcome
        System.out.println(GREETING_MESSAGE);

        // output how to escape
        System.out.println(ESCAPE_MESSAGE);

        try (// construct Scanner and begin interaction
                var scanner = new Scanner(System.in)) {

            // Prompt for topic: ask if they want to see animals
            System.out.println("Do you want to see our specials (y/n)?");
            var interestInput = scanner.next();

            // if yes, show list
            if (interestInput.toUpperCase().startsWith("Y")) {

                // declare an int for the custom type number input
                int typeNumberInput;

                // declare a boolean for isValid
                boolean isValid;

                // do the list prompt for the first time, loop back while valid
                do {
                    // Prompt for type: ask if they want to see our options
                    System.out.println();
                    System.out.println("-------------------------------------");
                    System.out.println("Which beverage would you like to see?");
                    System.out.println("Enter a number to choose, 0 to exit.");
                    // Run UtilityBuildSwitch to get autogenerated switch and menu
                    // Replace the menu below as it grows
                    // Remember to also change the value of NUMBER_CUSTOM_TYPES above.
                    System.out.print(" 1.Coffee              ");
                    System.out.print(" 2.Milk                ");
                    System.out.print(" 3.Tea                 ");
                    System.out.print(" 7.OrangeBreeze              ");
                    System.out.print(" 8.CoconutWaterSlush                ");
                    System.out.print(" 9.RaspberryVanillaSoda                 ");
                     System.out.print(" 10.MelonSorbetFloat                 ");
		    System.out.print(" 11.Apple Juice                 ");
                    System.out.print(" 12.Bananna Juice                 ");
                    System.out.print(" 13.Mango Juice                ");
			System.out.print(" 14.Peach Smoothie                ");
			System.out.print(" 15.Blueberries Smoothie               ");
			System.out.print(" 16. Dragon Fruit Smoothie               ");
			System.out.print(" 17. PineApple Smmothie               ");
			System.out.print("18.PediaLyte            ");
                    System.out.print("19.ORS            ");
                    System.out.print("20.LMNT            ");
                    System.out.print("21.Essentia            ");
                    
                    // END PASTE - right-click / Format
                    System.out.println();
                    try {
                        typeNumberInput = scanner.nextInt();
                    } catch (Exception ex) {
                        typeNumberInput = 0;
                    }

                    // set isValid if >= 1 and <= number of custom types
                    isValid = typeNumberInput >= 1 && typeNumberInput <= NUMBER_CUSTOM_TYPES;

                    // switch by custom type - autogenerate with AppBuildSwitch.java
                    switch (typeNumberInput) {

                        // Run UtilityBuildSwitch.java and paste the 
                        // autogenerated switch code here............
                        case 1 -> {
                            var b = new Coffee("Coffee");
                            var n = b.getName();
                            var d = b.getDescription();
                            System.out.println("I'm " + n + ", a " + d + ".");
                        }
                        case 2 -> {
                            var b = new Milk("Milk");
                            var n = b.getName();
                            var d = b.getDescription();
                            System.out.println("I'm " + n + ", a " + d + ".");
                        }
                        case 3 -> {
                            var b = new Tea("Tea");
                            var n = b.getName();
                            var d = b.getDescription();
                            System.out.println("I'm " + n + ", a " + d + ".");
                        }
                        case 4 -> {
                            var coke = new Coke(12.50, "Coke", 12.50, 75.00);
                            System.out.println("I'm " + coke.getName() + ", a " + coke.getDescription() + ".");
                        }
                        case 5 -> {
                            var sprite = new Sprite(15.00, "Sprite", 10.00, 75.00);
                            System.out.println("I'm " + sprite.getName() + ", a " + sprite.getDescription()+ ".");
                        } 
                        case 6 -> {
                            var gingerale = new Gingerale(25.00, "gingerale", 10.00, 65.00);
                            System.out.println("I'm " + gingerale.getName() + ", a " + gingerale.getDescription()+ ".");
                        } 
                            case 7 -> {
                            var b = new OrangeBreeze(10.00,1,"OrangeBreeze");
                            var n = b.getName();
                            var d = b.calculatebill();
                            System.out.println("I'm " + n + ", my price is  " + d + ".");
                        }
                        case 8 -> {
                            var b = new CoconutWaterSlush(20.00,1,"CoconutWaterSlush");
                            var n = b.getName();
                            var d = b.calculatebill();
                            System.out.println("I'm " + n + ", my price is  " + d + ".");
                        }
                        case 9 -> {
                            var b = new RaspberryVanillaSoda(25.00,1,"RaspberryVanillaSoda");
                            var n = b.getName();
                            var d = b.calculatebill();
                            System.out.println("I'm " + n + ", my price is  " + d + ".");
                        }
						case 10 -> {
                            var b = new MelonSorbetFloat(35.00f,1,"MelonSorbetFloat");
                            var n = b.getName();
                            var d = b.calculatebill();
                            System.out.println("I'm " + n + ", my price is  " + d + ".");
                        }
				    case 11 -> {
                            var b = new AppleJuice("Apple Juice");
                            var n = b.getName();
                            var d = b.getDescription();
                            var c = b.juiceCost();
                            System.out.println("I'm " + n + ", a " + d + ".");
                            System.out.println(c);
                        }
                        case 12 -> {
                            var b = new BanannaJuice("bananna");
                            var n = b.getName();
                            var d = b.getDescription();
                            var c = b.juiceCost();
                            System.out.println("I'm " + n + ", a " + d + ".");
                            System.out.println("Cost of Banana Juice is "+c);
                        }
                        case 13 -> {
                            var b = new MangoJuice("Mango Juice");
                            var n = b.getName();
                            var d = b.getDescription();
                            var c = b.juiceCost();
                            System.out.println("I'm " + n + ", a " + d + ".");
                            System.out.println(c);
                        }
			   
                       case 14 -> {
                            var b = new PeachSmoothie(25.5, 9.0, 5, 5, "Peach Smoothie");
                            var n = b.getName();
                            var d = b.getDescription();
                            var e = b.calCost();
                            System.out.println("I'm " + n + " , " + d + ","+e);
                        }
                        
                        case 15 -> {
                            var b = new BlueBerriesSmoothie(45.5, 5.0, 7, 3, "Blueberries Smoothie");
                            var n = b.getName();
                            var d = b.getDescription();
                            var e = b.calCost();
                            System.out.println("I'm " + n + " , " + d + ","+ e);
                        }
                        
                        case 16 -> {
                            var b = new DragonFruitSmoothie(7.0, 10, 6, "Dragon FriutSmoothie");
                            var n = b.getName();
                            var d = b.getDescription();
                            var e = b.calCost();
                            System.out.println("I'm " + n + " , " + d + ","+ e);
                        }
                        
                        case 17 -> {
                            var b = new PineAppleSmoothie(15.5, 8.0, 13, 9, "Pineapple Smoothie");
                            var n = b.getName();
                            var d = b.getDescription();
                            var e = b.calCost();
                            System.out.println("I'm " + n + " , " + d + ","+ e);
                        }
				    case 18 -> {
                            Pedialyte elec = new Pedialyte("Strawberry", "DR.Pedia", "bottle", "Pedialyte");
                            var nam = elec.getName();
                            var des = elec.getDescription();
                            var man = elec.getManufacture();
                            var typ = elec.getType();
                            

                            System.out.println("I'm " + nam + ", " + des + ", manufactured by " + man + " available in  " + typ + " ");
                            System.out.println("Mineral Content==>"+elec.calcMineralContent());
                            System.out.println("Flavour:"+elec.getFlavor());
                        }
                        case 19 -> {
                            ORS elec = new ORS("Strawberry", "DR.Pedia", "packet", "ORS");
                            var nam = elec.getName();
                            var des = elec.getDescription();
                            var man = elec.getManufacture();
                            var typ = elec.getType();
                            

                            System.out.println("I'm " + nam + ", " + des + ", manufactured by " + man + " available in  " + typ + " ");
                            System.out.println("Mineral Content==>"+elec.calcMineralContent());
                            System.out.println("Flavour:"+elec.getFlavor());
                        }
                        case 20 -> {
                            LMNT elec = new LMNT(530.50, "DR.Pedia", "bottle", "LMNT");
                            var nam = elec.getName();
                            var des = elec.getDescription();
                            var man = elec.getManufacture();
                            var typ = elec.getType();
                            

                            System.out.println("I'm " + nam + ", " + des + ", manufactured by " + man + " available in  " + typ + " ");
                            System.out.println("Mineral Content==>"+elec.calcMineralContent());
                            System.out.println("Calories:"+elec.getCalories());
                        }
                        case 21 -> {
                            Essentia elec = new Essentia(55, "DR.Pedia", "packet", "Essentia");
                            var nam = elec.getName();
                            var des = elec.getDescription();
                            var man = elec.getManufacture();
                            var typ = elec.getType();
                            

                            System.out.println("I'm " + nam + ", " + des + ", manufactured by " + man + " available in  " + typ + " ");
                            System.out.println("Mineral Content==>"+elec.calcMineralContent());
                            System.out.println("Price:"+ elec.getPrice());
                        }
                         
                        //// END PASTE (right-click and Format )
                        default -> {
                        }

                    }

                    // while the input is valid, we loop back
                } while (isValid);

            }
        }

        // output goodbye
        System.out.println(GOODBYE_MESSAGE);
    }
}